controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    bot_controller:
      type: diff_drive_controller/DiffDriveController

bot_controller:
  ros__parameters:
    left_wheel_names: ["wheel_front_left_joint", "wheel_back_left_joint"]
    right_wheel_names: ["wheel_front_right_joint", "wheel_back_right_joint"]

    wheel_separation: 0.8
    wheel_radius: 0.1

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0  # m/s
        has_acceleration_limits: true
        max_acceleration: 0.5  # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.5  # rad/s
        has_acceleration_limits: true
        max_acceleration: 1.0  # rad/s^2

    # Publish odom tf
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    # Other parameters
    enable_odom_tf: true
    cmd_vel_timeout: 0.5  # seconds
    publish_limited_velocity: true
    use_stamped_vel: false