controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    bot_controller :
      type: diff_drive_controller/DiffDriveController

bot_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ['wheel_front_left_joint', 'wheel_back_left_joint']
    right_wheel_names: ['wheel_front_right_joint', 'wheel_back_right_joint']

    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

    wheel_separation: 0.8
    wheel_radius: 0.10
    wheels_per_side: 2

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    use_stamped_vel: false
    
    #cmd_vel_topic: "/cmd_vel"
    #cmd_vel_timeout: 0.5

    #base_frame_id: base_link
    #odom_frame_id: odom

    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true

    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_acceleration: 0.5
        max_velocity: 1.0
    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_acceleration: 1.0
        max_velocity: 1.5