controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    bot_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

bot_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: true

    # Modified for 4-wheel configuration
    left_wheel_names: ['wheel_front_left_joint', 'wheel_back_left_joint']
    right_wheel_names: ['wheel_front_right_joint', 'wheel_back_right_joint']

    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

    # Modified wheel separation based on URDF (distance between left and right wheels)
    wheel_separation: 0.8  # Based on your URDF (distance between y=-0.4 and y=0.4)

    # Wheel radius from URDF
    wheel_radius: 0.10  # Based on your URDF cylinder radius

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    cmd_vel_timeout: 0.5
    base_frame_id: base_link

    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0  # m/s
        min_velocity: -0.5 # m/s
        has_acceleration_limits: true
        max_acceleration: 0.8  # m/s^2
        min_acceleration: -0.4 # m/s^2
        has_jerk_limits: false
        max_jerk: 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.7  # rad/s
        has_acceleration_limits: true
        max_acceleration: 1.5  # rad/s^2
        has_jerk_limits: false
        max_jerk: 2.5  # rad/s^3